<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@400;700&family=Noto+Serif+SC:wght@400;700&display=swap"/>
<link rel="stylesheet" href="css/styles.css" />

<!-- Begin Jekyll SEO tag v2.7.1 -->
<meta name="generator" content="Jekyll v3.9.0" />
<!--
<meta name="description" content="desc" />
<meta property="og:title" content="title" />
<meta property="og:description" content="desc" />
<meta property="og:site_name" content="site_name" />
-->
<link rel="canonical" href="/" />
<meta property="og:url" content="/" />
