  <nav class="desktop">
    <h1><a href="./index.html">Bangya Liu</a></h1>
    <ul><li><a href="./index.html" title="" >About Me</a></li></ul>
    <ul><li><a href="./proj.html" title="" >Project</a></li></ul>
    <ul><li><a href="./pub.html" title="" >Publication</a></li></ul>
    <ul><li><a href="./res.html" title="" >Resource</a></li></ul>
    <ul><li><a href="./life.html" title="" >Nichijou</a></li></ul>
  </nav>
  <nav class="mobile">
    <details>
      <summary><a href="./index.html">Bangya Liu</a></summary>
    <ul><li><a href="./index.html" title="" >About Me</a></li></ul>
    <ul><li><a href="./proj.html" title="" >Project</a></li></ul>
    <ul><li><a href="./pub.html" title="" >Publication</a></li></ul>
    <ul><li><a href="./res.html" title="" >Resource</a></li></ul>
    <ul><li><a href="./life.html" title="" >Nichijou</a></li></ul>
    </details>
  </nav>